config/routes.rb
Rails.application.routes.draw do
  captcha_route
  devise_for :users
  
  resources :categories

  resources :transactions do
    collection do
      get '/new/income', to: 'transactions#new_income'
      get '/new/expense', to: 'transactions#new_expense'
    end
  end

  root 'transactions#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  enum category_type: [ :income, :expense ]
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  
  mount_uploader :attachment, AttachmentUploader

  after_save :update_user_amount
  after_destroy :update_user_amount

  before_save :validate_quantity

  
  enum trans_type: [ :income, :expense ]

  validates_presence_of :quantity

  belongs_to :user
  belongs_to :category

  def quantity
    read_attribute(:quantity).to_f.abs
  end

  def validate_quantity
    value = quantity.to_f.abs

    if self.trans_type.to_sym == :expense
      self.quantity = value * -1
      puts "dfdfdfdferer"
    else
      self.quantity = value
    end
  end

  def update_user_amount
    self.user.current_amount = Transaction.where(user_id: self.user.id).sum(:quantity)
    self.user.save
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def before_create
    self.current_ammount = 0.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(user_id: current_user.id)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: catgories_path }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: categories_path }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_type)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit, :update, :destroy]

  def index
     @transactions = Transaction.where(user_id: current_user.id)
  end
  
  def new_income
    @transaction  = Transaction.new(trans_type: :income)
    render 'new'
  end

  def new_expense
    @transaction  = Transaction.new(trans_type: :expense)
    render 'new'
  end
  
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: transactions_path }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: transactions_path }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:caption, :quantity, :category_id, :trans_type, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .form_group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form_group
    = f.label :category_type
    = f.select :category_type, options_for_select(Category.category_types.collect { |s| [s[0].humanize, s[0]] }, selected: @category.category_type), {}, { class: "form-control"}

  hr

  .form-group
    = f.submit 'Save', class: 'btn btn-primary'

app/views/categories/edit.html.slim
h1 Editing category
hr

== render 'form'

app/views/categories/index.html.slim
h1 Listing categories
hr

.pull-right
  = link_to 'New Category', new_category_path, class: 'btn btn-primary'

table.table.table-striped
  thead
    tr
      th Name
      th Category type
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = category.category_type
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/categories/new.html.slim
h1 New category
hr
== render 'form'

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name
p
  strong Category type:
  = @category.category_type

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Finance Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

    -if current_user
      #wrapper

        /! Navigation
        nav.navbar.navbar-default.navbar-static-top role="navigation" style=("margin-bottom: 0")
          .navbar-header
            button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand href="#"  Finance manager
          /! /.navbar-header
          
          .navbar-default.sidebar role="navigation"
            .sidebar-nav.navbar-collapse
              ul#side-menu.nav
                li
                  = link_to "Transactions", transactions_path
                li
                  = link_to "Categories", categories_path
                li
                  = link_to "Signout", destroy_user_session_path, method: :delete

        #page-wrapper
          .container-fluid
            - if flash[:notice]
              .alert.alert-success
                = flash[:notice]
            = yield
    - else
      .container-fluid
        - if flash[:notice]
          .alert.alert-success
            = flash[:notice]
        = yield
     

app/views/transactions/_form.html.slim
= form_for @transaction do |f|
  = f.hidden_field :trans_type

  - if @transaction.errors.any?
    #error_explanation.
      h5 = "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      .alert.alert-danger
        - @transaction.errors.full_messages.each do |message|
          p = message

  .form-group
    = f.label "Caption"
    = f.text_field :caption, class: 'form-control'

  .form-group
    = f.label "Quantity"
    = f.text_field :quantity, class: 'form-control'

  .form-group
    = f.label "Category"
    = f.select :category_id, options_from_collection_for_select(Category.where(category_type: Transaction.trans_types[@transaction.trans_type]), "id", "name"), {}, { class: "form-control"}

  .form-group
    = f.label "Attachment"
    = f.file_field :attachment

  hr
  .form-group
    = f.submit class: 'btn btn-primary'

app/views/transactions/edit.html.slim
h1= "Edit #{@transaction.trans_type.capitalize}"
hr
= render "form"

app/views/transactions/index.html.slim
h1 Transactions
hr

h3= "Current Balance: #{number_to_currency(current_user.current_amount, unit: '$')}"

.clearfix
  .pull-right
    = link_to "Create New Income", new_income_transactions_path, class: 'btn btn-success'
  .pull-right
    = link_to "Create New Expense", new_expense_transactions_path, class: 'btn btn-primary'
hr

table.table.table-striped
  tr
    th Value
    th Note
    th Category
    th Type
    th Date
    th Attachment
    th
    th
   
  - @transactions.each do |transaction|
    tr
      td= "#{number_to_currency(transaction.quantity, unit: '$')}"
      td= transaction.caption
      td= transaction.trans_type
      td
        - if transaction.category
          = transaction.category.name
      td= transaction.created_at
      td
        - if transaction.attachment.url
          = link_to "Show Attachment", transaction.attachment.url, target: "_blank"
      td
        = link_to "Edit", edit_transaction_path(transaction)
      td
        = link_to "Delete", transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' }

app/views/transactions/new.html.slim
h1= "New #{@transaction.trans_type.capitalize}"
hr
= render "form"